name: beetrave

services:
  app:
    build:
      context: ./app
      target: production
    ports:
      - "5173:5173"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: beetrave
      POSTGRES_PASSWORD: beetrave
      POSTGRES_DB: beetrave
      POSTGRES_PORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  postgres_data:
