name: beetrave

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "5173:5173"
    depends_on:
      - db
    volumes:
      - .:/app
      - /local/path/to/beets-config:/container/path/to/beets-config
      - /local/path/to/library-root:/container/path/to/library-root
    environment:
      - NODE_ENV=production
      - BEETS_LIBRARY_ROOT=/container/path/to/library-root
      - BEETS_LIBRARY_DB=/container/path/to/beets-config/library.db
      - POSTGRES_DATABASE_HOST=localhost
      - POSTGRES_DATABASE_PORT=5433
      - POSTGRES_DATABASE_USER=beetrave
      - POSTGRES_DATABASE_PASSWORD=beetrave
      - POSTGRES_DATABASE_NAME=beetrave

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: beetrave
      POSTGRES_PASSWORD: beetrave
      POSTGRES_DB: beetrave
      POSTGRES_PORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  postgres_data:
