name: beetrave

services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 16661
      DATABASE_USER: postgres
      DATABASE_PASSWORD: example
      DATABASE_NAME: mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "16661:16661"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
