name: beetrave

services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: beetrave
      POSTGRES_PASSWORD: beetrave
      POSTGRES_DB: beetrave
      POSTGRES_PORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  postgres_data:
